### ISSUE TITLE
ERROR: Failed to parse POMs while Project build using Jenkins   #bms241093

### ISSUE THREAD

**Issue by bms241093** [bms241093/Angular-7-with-Fusion-Chart#2]
2:12:22 Started by user admin
12:12:22 Building in workspace E:\software\Jenkins\JenkinsHomeDirectory\workspace\Angular7SpringBoot
12:12:22 No credentials specified
12:12:22 Cloning the remote Git repository
12:12:22 Cloning repository https://github.com/bms241093/Angular7-SpringBoot.git
12:12:22  > C:\Program Files\Git\bin\git.exe init E:\software\Jenkins\JenkinsHomeDirectory\workspace\Angular7SpringBoot # timeout=10
12:12:22 Fetching upstream changes from https://github.com/bms241093/Angular7-SpringBoot.git
12:12:22  > C:\Program Files\Git\bin\git.exe --version # timeout=10
12:12:22  > C:\Program Files\Git\bin\git.exe fetch --tags --force --progress https://github.com/bms241093/Angular7-SpringBoot.git +refs/heads/*:refs/remotes/origin/*
12:12:25  > C:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/bms241093/Angular7-SpringBoot.git # timeout=10
12:12:25  > C:\Program Files\Git\bin\git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
12:12:25  > C:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/bms241093/Angular7-SpringBoot.git # timeout=10
12:12:25 Fetching upstream changes from https://github.com/bms241093/Angular7-SpringBoot.git
12:12:25  > C:\Program Files\Git\bin\git.exe fetch --tags --force --progress https://github.com/bms241093/Angular7-SpringBoot.git +refs/heads/*:refs/remotes/origin/*
12:12:26  > C:\Program Files\Git\bin\git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
12:12:26  > C:\Program Files\Git\bin\git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
12:12:26 Checking out Revision 49e8c9d0c411fff63ad03bd5ecd00ac36812e19e (refs/remotes/origin/master)
12:12:26  > C:\Program Files\Git\bin\git.exe config core.sparsecheckout # timeout=10
12:12:26  > C:\Program Files\Git\bin\git.exe checkout -f 49e8c9d0c411fff63ad03bd5ecd00ac36812e19e
12:12:28 Commit message: "Set theme jekyll-theme-time-machine"
12:12:28 First time build. Skipping changelog.
12:12:31 Parsing POMs
12:12:32 ERROR: Failed to parse POMs
12:12:32 hudson.maven.MavenEmbedderException: 1 problem was encountered while building the effective settings
12:12:32 [FATAL] Non-readable settings C:\Program Files\apache-maven-3.6.1\bin: C:\Program Files\apache-maven-3.6.1\bin (Access is denied) @ C:\Program Files\apache-maven-3.6.1\bin
12:12:32 
12:12:32 	at hudson.maven.MavenEmbedder.<init>(MavenEmbedder.java:128)
12:12:32 	at hudson.maven.MavenEmbedder.<init>(MavenEmbedder.java:109)
12:12:32 	at hudson.maven.MavenEmbedder.<init>(MavenEmbedder.java:136)
12:12:32 	at hudson.maven.MavenUtil.createEmbedder(MavenUtil.java:211)
12:12:32 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1322)
12:12:32 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1125)
12:12:32 	at hudson.FilePath.act(FilePath.java:1075)
12:12:32 	at hudson.FilePath.act(FilePath.java:1058)
12:12:32 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:986)
12:12:32 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:691)
12:12:32 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
12:12:32 	at hudson.model.Run.execute(Run.java:1816)
12:12:32 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
12:12:32 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:12:32 	at hudson.model.Executor.run(Executor.java:429)
12:12:32 Caused by: hudson.maven.MavenEmbedderException: 1 problem was encountered while building the effective settings
12:12:32 [FATAL] Non-readable settings C:\Program Files\apache-maven-3.6.1\bin: C:\Program Files\apache-maven-3.6.1\bin (Access is denied) @ C:\Program Files\apache-maven-3.6.1\bin

**Comment by bms241093** [comment]
![FailedtoparsePOM](https://user-images.githubusercontent.com/49841743/58942232-03815900-879b-11e9-9d81-e6be5edd827e.PNG)

Kindly refer photo
